# Generated by Django 5.2.11 on 2026-02-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_account_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactaccount',
            name='bank_name',
            field=models.CharField(max_length=200),
        ),
    ]
