# Generated by Django 5.2.11 on 2026-02-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_account_account_number_alter_loan_person_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='iban',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_name',
            field=models.CharField(choices=[('Cash', 'Cash'), ('JazzCash', 'JazzCash'), ('EasyPaisa', 'EasyPaisa'), ('Nayapay', 'Nayapay'), ('SadaPay', 'SadaPay'), ('Bank Alfalah', 'Bank Alfalah'), ('Meezan Bank', 'Meezan Bank')], max_length=50),
        ),
    ]
