# Generated by Django 5.2.11 on 2026-02-24 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_contactaccount_bank_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='internaltransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='amount_positive'),
        ),
    ]
