# Generated by Django 5.2.11 on 2026-02-22 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_account_iban_alter_account_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tracker.contact'),
        ),
    ]
