# Generated by Django 5.2.11 on 2026-02-24 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_internaltransaction_amount_positive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='internaltransaction',
            name='amount_positive',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='balance_positive'),
        ),
        migrations.AddConstraint(
            model_name='internaltransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='internal_transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transactionsplit',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_split_amount_positive'),
        ),
    ]
