# Generated by Django 5.2.11 on 2026-02-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_transaction_account_transactionsplit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank_name',
            field=models.CharField(choices=[('Cash', 'Cash'), ('JazzCash', 'JazzCash'), ('EasyPaisa', 'EasyPaisa'), ('Nayapay', 'Nayapay'), ('SadaPay', 'SadaPay'), ('Bank Alfalah', 'Bank Alfalah'), ('Meezan Bank', 'Meezan Bank'), ('HBL', 'HBL')], max_length=50),
        ),
    ]
