# Generated by Django 5.2.11 on 2026-02-25 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_internaltransaction_amount_positive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='expense_category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='income_source',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='note',
        ),
        migrations.AddField(
            model_name='transactionsplit',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_splits', to='tracker.expensecategory'),
        ),
        migrations.AddField(
            model_name='transactionsplit',
            name='income_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_splits', to='tracker.incomesource'),
        ),
        migrations.AddField(
            model_name='transactionsplit',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
