# Generated by Django 5.2.11 on 2026-02-23 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_account_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='tracker.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_contact_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='tracker.contactaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('LOAN_TAKEN', 'Loan Taken'), ('MONEY_LENT', 'Money Lent'), ('REPAYMENT', 'Repayment (Paying back loan taken)'), ('REIMBURSEMENT', 'Reimbursement (Getting back money lent)'), ('TRANSFER', 'Transfer')], max_length=20),
        ),
    ]
