# Generated by Django 5.2.11 on 2026-02-23 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_transaction_to_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsplit',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splits', to='tracker.contact'),
        ),
        migrations.AddField(
            model_name='transactionsplit',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splits', to='tracker.loan'),
        ),
        migrations.AddField(
            model_name='transactionsplit',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('LOAN_TAKEN', 'Loan Taken'), ('MONEY_LENT', 'Money Lent'), ('REPAYMENT', 'Repayment (Paying back loan taken)'), ('REIMBURSEMENT', 'Reimbursement (Getting back money lent)'), ('TRANSFER', 'Transfer')], default='EXPENSE', max_length=20),
        ),
    ]
