# Generated by Django 5.2.11 on 2026-02-26 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_account_unique_account_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tracker.contact'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='contact_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='tracker.contactaccount'),
        ),
    ]
