# Generated by Django 5.2.11 on 2026-02-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_transaction_contact_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contactaccount',
            constraint=models.UniqueConstraint(fields=('contact', 'account_number', 'bank_name'), name='unique_account_per_contact'),
        ),
    ]
