# Generated by Django 5.2.11 on 2026-02-28 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_contactaccount_unique_account_per_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='internal_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tracker.internaltransaction'),
        ),
    ]
