# Generated by Django 5.2.11 on 2026-03-01 16:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_expenses', to='tracker.expensecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['end_date'],
                'indexes': [models.Index(fields=['user', 'is_completed'], name='tracker_pla_user_id_fe4ecd_idx'), models.Index(fields=['user', 'start_date', 'end_date'], name='tracker_pla_user_id_60e56d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='planned_expense_end_after_start'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='planned_expense_amount_positive')],
            },
        ),
    ]
