# Generated by Django 5.2.11 on 2026-03-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_plannedexpense'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transactionaccount',
            index=models.Index(fields=['transaction'], name='tracker_tra_transac_746ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionaccount',
            index=models.Index(fields=['account'], name='tracker_tra_account_8c2fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionsplit',
            index=models.Index(fields=['transaction_account'], name='tracker_tra_transac_e02876_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionsplit',
            index=models.Index(fields=['type'], name='tracker_tra_type_21918e_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionsplit',
            index=models.Index(fields=['expense_category'], name='tracker_tra_expense_00f8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionsplit',
            index=models.Index(fields=['income_source'], name='tracker_tra_income__0acfb5_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionsplit',
            index=models.Index(fields=['loan'], name='tracker_tra_loan_id_bcba51_idx'),
        ),
    ]
