# Generated by Django 5.2.11 on 2026-03-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_transactionaccount_tracker_tra_transac_746ab5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedexpense',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='plannedexpense',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
